server:
  port: 8080

spring:
  application:
    name: api.techchristian.series
  datasource:
    url: jdbc:mysql://localhost:3306/seriesdb?createDatabaseIfNotExist=true
    username: { USERNAME_DATABASE }
    password: { PASSWORD_DATABASE }
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: {PORT_REDIS}
  cache:
    type: redis

springdoc:
  api-docs:
    path: /series-docs
  swagger-ui:
    path: /series-docs.html
  packages-to-scan: br.com.api.techchristian.series.controller

jwt:
  expiration: ${JWT_EXPIRATION}
  key: ${JWT_KEY}