version: "3.8"

services:
 app:
   build:
    context: ..
    dockerfile: Dockerfile
   container_name: series_movies-app
   ports:
     - "8000:8080"
   depends_on:
     mysql:
       condition: service_healthy
     redis:
       condition: service_started

   env_file:
     - .env
   environment:
     SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
     SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
     SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
     SPRING_JPA_HIBERNATE_DDL_AUTO: update
     SPRING_JPA_SHOW_SQL: "true"
 mysql:
   image: mysql:8.0
   container_name: mysql-db-series_movies
   restart: always
   env_file:
       - .env
   ports:
       - "3307:3306"
   volumes:
      - mysql-data:/var/lib/mysql
   healthcheck:
       test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD" ]
       interval: 10s
       timeout: 5s
       retries: 5
 redis:
      image: redis:7.0
      container_name: redis-db-series_movies
      ports:
        - "6379:6379"
volumes:
  mysql-data:
